familjekontor/app/forms/governance.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SelectField, DateField, DecimalField,
                     IntegerField, TextAreaField, BooleanField, SubmitField)
from wtforms.validators import DataRequired, Optional, Length, NumberRange

from app.models.governance import BOARD_ROLE_LABELS, MEETING_TYPE_LABELS, ACQUISITION_TYPE_LABELS


ROLE_CHOICES = [('', '-- Välj roll --')] + [
    (k, v) for k, v in BOARD_ROLE_LABELS.items()
]

MEETING_TYPE_CHOICES = [
    (k, v) for k, v in MEETING_TYPE_LABELS.items()
]

ACQUISITION_CHOICES = [
    (k, v) for k, v in ACQUISITION_TYPE_LABELS.items()
]


class BoardMemberForm(FlaskForm):
    name = StringField('Namn', validators=[DataRequired(), Length(max=200)])
    personal_number = StringField('Personnummer', validators=[Optional(), Length(max=13)])
    role = SelectField('Roll', choices=ROLE_CHOICES, validators=[DataRequired()])
    title = StringField('Titel', validators=[Optional(), Length(max=100)])
    appointed_date = DateField('Tillträdesdag', validators=[DataRequired()])
    end_date = DateField('Avgångsdag', validators=[Optional()])
    appointed_by = StringField('Utsedd av', validators=[Optional(), Length(max=100)])
    email = StringField('E-post', validators=[Optional(), Length(max=120)])
    phone = StringField('Telefon', validators=[Optional(), Length(max=20)])
    submit = SubmitField('Spara')


class ShareClassForm(FlaskForm):
    name = StringField('Aktieslag', validators=[DataRequired(), Length(max=50)])
    votes_per_share = IntegerField('Röster per aktie', default=1,
                                    validators=[DataRequired(), NumberRange(min=1)])
    par_value = DecimalField('Kvotvärde (SEK)', places=2, validators=[Optional()])
    total_shares = IntegerField('Totalt antal aktier', validators=[DataRequired(), NumberRange(min=1)])
    submit = SubmitField('Spara')


class ShareholderForm(FlaskForm):
    name = StringField('Namn', validators=[DataRequired(), Length(max=200)])
    personal_or_org_number = StringField('Person-/Org.nummer', validators=[Optional(), Length(max=20)])
    address = StringField('Adress', validators=[Optional(), Length(max=300)])
    is_company = BooleanField('Är juridisk person')
    submit = SubmitField('Spara')


class HoldingForm(FlaskForm):
    share_class_id = SelectField('Aktieslag', coerce=int, validators=[DataRequired()])
    shares = IntegerField('Antal aktier', validators=[DataRequired(), NumberRange(min=1)])
    acquired_date = DateField('Förvärvsdatum', validators=[DataRequired()])
    acquisition_type = SelectField('Förvärvstyp', choices=ACQUISITION_CHOICES,
                                    validators=[DataRequired()])
    price_per_share = DecimalField('Pris per aktie (SEK)', places=2, validators=[Optional()])
    note = TextAreaField('Anteckning', validators=[Optional(), Length(max=500)])
    submit = SubmitField('Lägg till')


class DividendForm(FlaskForm):
    fiscal_year_id = SelectField('Räkenskapsår', coerce=int, validators=[DataRequired()])
    decision_date = DateField('Beslutsdatum', validators=[DataRequired()])
    total_amount = DecimalField('Totalt belopp (SEK)', places=2, validators=[DataRequired()])
    amount_per_share = DecimalField('Belopp per aktie', places=4, validators=[Optional()])
    share_class_id = SelectField('Aktieslag', coerce=int, validators=[Optional()])
    record_date = DateField('Avstämningsdag', validators=[Optional()])
    payment_date = DateField('Utbetalningsdag', validators=[Optional()])
    submit = SubmitField('Spara')


class AGMForm(FlaskForm):
    meeting_date = DateField('Mötesdatum', validators=[DataRequired()])
    meeting_type = SelectField('Mötestyp', choices=MEETING_TYPE_CHOICES,
                                validators=[DataRequired()])
    fiscal_year_id = SelectField('Avser räkenskapsår', coerce=int, validators=[Optional()])
    chairman = StringField('Ordförande', validators=[Optional(), Length(max=200)])
    minutes_taker = StringField('Protokollförare', validators=[Optional(), Length(max=200)])
    attendees = TextAreaField('Närvarande', validators=[Optional()])
    resolutions = TextAreaField('Beslut', validators=[Optional()])
    submit = SubmitField('Spara')

familjekontor/app/routes/governance.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from flask_login import login_required, current_user
from app.extensions import db
from app.models.accounting import FiscalYear
from app.models.governance import (
    BoardMember, ShareClass, Shareholder, ShareholderHolding,
    DividendDecision, AGMMinutes, BOARD_ROLE_LABELS,
)
from app.forms.governance import (
    BoardMemberForm, ShareClassForm, ShareholderForm,
    HoldingForm, DividendForm, AGMForm,
)
from app.services.governance_service import (
    create_board_member, update_board_member, end_appointment,
    get_board_members, create_share_class, get_share_classes,
    create_shareholder, get_shareholders, add_holding,
    get_ownership_summary, get_share_register,
    create_dividend_decision, pay_dividend, get_dividends,
    create_agm_minutes, get_agm_history, get_agm,
)

governance_bp = Blueprint('governance', __name__)


def _get_active_context():
    company_id = session.get('active_company_id')
    if not company_id:
        return None, None, None
    from app.models.company import Company
    company = db.session.get(Company, company_id)
    active_fy = FiscalYear.query.filter_by(
        company_id=company_id, status='open'
    ).order_by(FiscalYear.year.desc()).first()
    return company_id, company, active_fy


# ---------------------------------------------------------------------------
# Board Members
# ---------------------------------------------------------------------------

@governance_bp.route('/board')
@login_required
def board():
    company_id, company, active_fy = _get_active_context()
    if not company_id:
        flash('Välj ett företag först.', 'warning')
        return redirect(url_for('companies.index'))

    show_all = request.args.get('all') == '1'
    members = get_board_members(company_id, active_only=not show_all)
    return render_template('governance/board.html',
                           members=members, show_all=show_all,
                           role_labels=BOARD_ROLE_LABELS)


@governance_bp.route('/board/new', methods=['GET', 'POST'])
@login_required
def board_new():
    company_id, company, active_fy = _get_active_context()
    if not company_id:
        flash('Välj ett företag först.', 'warning')
        return redirect(url_for('companies.index'))
    if current_user.is_readonly:
        flash('Du har inte behörighet.', 'danger')
        return redirect(url_for('governance.board'))

    form = BoardMemberForm()
    if form.validate_on_submit():
        data = {
            'name': form.name.data,
            'personal_number': form.personal_number.data,
            'role': form.role.data,
            'title': form.title.data,
            'appointed_date': form.appointed_date.data,
            'end_date': form.end_date.data,
            'appointed_by': form.appointed_by.data,
            'email': form.email.data,
            'phone': form.phone.data,
        }
        try:
            member = create_board_member(company_id, data, created_by=current_user.id)
            flash(f'{member.name} tillagd som {member.role_label}.', 'success')
            return redirect(url_for('governance.board'))
        except ValueError as e:
            flash(str(e), 'danger')

    return render_template('governance/board_form.html', form=form, edit=False)


@governance_bp.route('/board/<int:member_id>/edit', methods=['GET', 'POST'])
@login_required
def board_edit(member_id):
    company_id, company, active_fy = _get_active_context()
    if not company_id:
        flash('Välj ett företag först.', 'warning')
        return redirect(url_for('companies.index'))
    if current_user.is_readonly:
        flash('Du har inte behörighet.', 'danger')
        return redirect(url_for('governance.board'))

    member = db.session.get(BoardMember, member_id)
    if not member or member.company_id != company_id:
        flash('Styrelseledamot hittades inte.', 'danger')
        return redirect(url_for('governance.board'))

    form = BoardMemberForm(obj=member)
    if form.validate_on_submit():
        data = {
            'name': form.name.data,
            'personal_number': form.personal_number.data,
            'role': form.role.data,
            'title': form.title.data,
            'appointed_date': form.appointed_date.data,
            'end_date': form.end_date.data,
            'appointed_by': form.appointed_by.data,
            'email': form.email.data,
            'phone': form.phone.data,
        }
        try:
            update_board_member(member.id, data)
            flash('Styrelseledamot uppdaterad.', 'success')
            return redirect(url_for('governance.board'))
        except ValueError as e:
            flash(str(e), 'danger')

    return render_template('governance/board_form.html', form=form, edit=True, member=member)


@governance_bp.route('/board/<int:member_id>/end', methods=['POST'])
@login_required
def board_end(member_id):
    company_id, company, active_fy = _get_active_context()
    if not company_id:
        flash('Välj ett företag först.', 'warning')
        return redirect(url_for('companies.index'))
    if current_user.is_readonly:
        flash('Du har inte behörighet.', 'danger')
        return redirect(url_for('governance.board'))

    member = db.session.get(BoardMember, member_id)
    if not member or member.company_id != company_id:
        flash('Styrelseledamot hittades inte.', 'danger')
        return redirect(url_for('governance.board'))

    from datetime import date
    end_date_str = request.form.get('end_date')
    if end_date_str:
        from datetime import datetime
        d = datetime.strptime(end_date_str, '%Y-%m-%d').date()
    else:
        d = date.today()

    try:
        end_appointment(member.id, d)
        flash(f'{member.name} avgått {d}.', 'success')
    except ValueError as e:
        flash(str(e), 'danger')

    return redirect(url_for('governance.board'))


# ---------------------------------------------------------------------------
# Shares & Ownership
# ---------------------------------------------------------------------------

@governance_bp.route('/shares')
@login_required
def shares():
    company_id, company, active_fy = _get_active_context()
    if not company_id:
        flash('Välj ett företag först.', 'warning')
        return redirect(url_for('companies.index'))

    share_classes = get_share_classes(company_id)
    shareholders = get_shareholders(company_id)
    ownership = get_ownership_summary(company_id)

    return render_template('governance/shares.html',
                           share_classes=share_classes,
                           shareholders=shareholders,
                           ownership=ownership)


@governance_bp.route('/shares/classes/new', methods=['GET', 'POST'])
@login_required
def share_class_new():
    company_id, company, active_fy = _get_active_context()
    if not company_id:
        flash('Välj ett företag först.', 'warning')
        return redirect(url_for('companies.index'))
    if current_user.is_readonly:
        flash('Du har inte behörighet.', 'danger')
        return redirect(url_for('governance.shares'))

    form = ShareClassForm()
    if form.validate_on_submit():
        data = {
            'name': form.name.data,
            'votes_per_share': form.votes_per_share.data,
            'par_value': form.par_value.data,
            'total_shares': form.total_shares.data,
        }
        try:
            sc = create_share_class(company_id, data, created_by=current_user.id)
            flash(f'Aktieslag "{sc.name}" skapat.', 'success')
            return redirect(url_for('governance.shares'))
        except Exception as e:
            flash(str(e), 'danger')

    return render_template('governance/share_class_form.html', form=form)


@governance_bp.route('/shares/shareholders/new', methods=['GET', 'POST'])
@login_required
def shareholder_new():
    company_id, company, active_fy = _get_active_context()
    if not company_id:
        flash('Välj ett företag först.', 'warning')
        return redirect(url_for('companies.index'))
    if current_user.is_readonly:
        flash('Du har inte behörighet.', 'danger')
        return redirect(url_for('governance.shares'))

    form = ShareholderForm()
    if form.validate_on_submit():
        data = {
            'name': form.name.data,
            'personal_or_org_number': form.personal_or_org_number.data,
            'address': form.address.data,
            'is_company': form.is_company.data,
        }
        try:
            sh = create_shareholder(company_id, data, created_by=current_user.id)
            flash(f'Aktieägare "{sh.name}" skapad.', 'success')
            return redirect(url_for('governance.shares'))
        except Exception as e:
            flash(str(e), 'danger')

    return render_template('governance/shareholder_form.html', form=form)


@governance_bp.route('/shares/holdings/new', methods=['GET', 'POST'])
@login_required
def holding_new():
    company_id, company, active_fy = _get_active_context()
    if not company_id:
        flash('Välj ett företag först.', 'warning')
        return redirect(url_for('companies.index'))
    if current_user.is_readonly:
        flash('Du har inte behörighet.', 'danger')
        return redirect(url_for('governance.shares'))

    share_classes = get_share_classes(company_id)
    shareholders = get_shareholders(company_id)

    form = HoldingForm()
    form.share_class_id.choices = [(sc.id, sc.name) for sc in share_classes]

    if form.validate_on_submit():
        shareholder_id = request.form.get('shareholder_id', type=int)
        if not shareholder_id:
            flash('Välj en aktieägare.', 'danger')
        else:
            data = {
                'share_class_id': form.share_class_id.data,
                'shares': form.shares.data,
                'acquired_date': form.acquired_date.data,
                'acquisition_type': form.acquisition_type.data,

familjekontor/app/templates/governance/agm_form.html
{% extends "base.html" %}
{% from "macros/breadcrumbs.html" import render_breadcrumbs %}
{% block title %}Ny bolagsstämma - PsalmGears{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumbs([
    {'title': 'Start', 'url': url_for('dashboard.index')},
    {'title': 'Bolagsstämmor', 'url': url_for('governance.agm_list')},
    {'title': 'Ny stämma'}
]) }}
{% endblock %}
{% block content %}
<h2><i class="bi bi-journal-bookmark"></i> Ny bolagsstämma</h2>

<div class="card mt-3">
    <div class="card-body">
        <form method="POST" data-unsaved-warning>
            {{ form.hidden_tag() }}
            <div class="row">
                <div class="col-md-4 mb-3">
                    <label class="form-label">{{ form.meeting_date.label.text }} <span class="text-danger">*</span></label>
                    {{ form.meeting_date(class="form-control", type="date") }}
                </div>
                <div class="col-md-4 mb-3">
                    <label class="form-label">{{ form.meeting_type.label.text }} <span class="text-danger">*</span></label>
                    {{ form.meeting_type(class="form-select") }}
                </div>
                <div class="col-md-4 mb-3">
                    <label class="form-label">{{ form.fiscal_year_id.label.text }}</label>
                    {{ form.fiscal_year_id(class="form-select") }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label class="form-label">{{ form.chairman.label.text }}</label>
                    {{ form.chairman(class="form-control") }}
                </div>
                <div class="col-md-6 mb-3">
                    <label class="form-label">{{ form.minutes_taker.label.text }}</label>
                    {{ form.minutes_taker(class="form-control") }}
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label">{{ form.attendees.label.text }}</label>
                {{ form.attendees(class="form-control", rows="3", placeholder="En person per rad") }}
            </div>
            <div class="mb-3">
                <label class="form-label">{{ form.resolutions.label.text }}</label>
                {{ form.resolutions(class="form-control", rows="6", placeholder="Protokollerade beslut") }}
            </div>
            <div class="d-flex gap-2">
                {{ form.submit(class="btn btn-primary") }}
                <a href="{{ url_for('governance.agm_list') }}" class="btn btn-outline-secondary">Avbryt</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

familjekontor/app/templates/governance/agm_list.html
{% extends "base.html" %}
{% from "macros/breadcrumbs.html" import render_breadcrumbs %}
{% block title %}Bolagsstämmor - PsalmGears{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumbs([
    {'title': 'Start', 'url': url_for('dashboard.index')},
    {'title': 'Bolagsstämmor'}
]) }}
{% endblock %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2><i class="bi bi-journal-bookmark"></i> Bolagsstämmor</h2>
    {% if not current_user.is_readonly %}
    <a href="{{ url_for('governance.agm_new') }}" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Ny bolagsstämma</a>
    {% endif %}
</div>

{% if agms %}
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Datum</th>
                <th>Typ</th>
                <th>Räkenskapsår</th>
                <th>Ordförande</th>
                <th>Protokollförare</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for agm in agms %}
            <tr class="cursor-pointer" data-href="{{ url_for('governance.agm_view', agm_id=agm.id) }}">
                <td>{{ agm.meeting_date.strftime('%Y-%m-%d') }}</td>
                <td>
                    <span class="badge {% if agm.meeting_type == 'arsstamma' %}bg-primary{% else %}bg-secondary{% endif %}">
                        {{ agm.meeting_type_label }}
                    </span>
                </td>
                <td>{% if agm.fiscal_year %}{{ agm.fiscal_year.year }}{% else %}-{% endif %}</td>
                <td>{{ agm.chairman or '' }}</td>
                <td>{{ agm.minutes_taker or '' }}</td>
                <td class="text-end">
                    <a href="{{ url_for('governance.agm_view', agm_id=agm.id) }}" class="btn btn-outline-secondary btn-sm"><i class="bi bi-eye"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div class="alert alert-info">Inga bolagsstämmor registrerade.</div>
{% endif %}
{% endblock %}

familjekontor/app/templates/governance/agm_view.html
{% extends "base.html" %}
{% from "macros/breadcrumbs.html" import render_breadcrumbs %}
{% block title %}Bolagsstämma {{ agm.meeting_date }} - PsalmGears{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumbs([
    {'title': 'Start', 'url': url_for('dashboard.index')},
    {'title': 'Bolagsstämmor', 'url': url_for('governance.agm_list')},
    {'title': agm.meeting_date.strftime('%Y-%m-%d')}
]) }}
{% endblock %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2>
        <i class="bi bi-journal-bookmark"></i>
        {{ agm.meeting_type_label }} {{ agm.meeting_date.strftime('%Y-%m-%d') }}
    </h2>
    <button onclick="window.print()" class="btn btn-outline-secondary no-print"><i class="bi bi-printer"></i> Skriv ut</button>
</div>

<div class="card mb-4">
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-md-3"><strong>Datum:</strong></div>
            <div class="col-md-9">{{ agm.meeting_date.strftime('%Y-%m-%d') }}</div>
        </div>
        <div class="row mb-3">
            <div class="col-md-3"><strong>Typ:</strong></div>
            <div class="col-md-9">{{ agm.meeting_type_label }}</div>
        </div>
        {% if agm.fiscal_year %}
        <div class="row mb-3">
            <div class="col-md-3"><strong>Avser räkenskapsår:</strong></div>
            <div class="col-md-9">{{ agm.fiscal_year.year }}</div>
        </div>
        {% endif %}
        {% if agm.chairman %}
        <div class="row mb-3">
            <div class="col-md-3"><strong>Ordförande:</strong></div>
            <div class="col-md-9">{{ agm.chairman }}</div>
        </div>
        {% endif %}
        {% if agm.minutes_taker %}
        <div class="row mb-3">
            <div class="col-md-3"><strong>Protokollförare:</strong></div>
            <div class="col-md-9">{{ agm.minutes_taker }}</div>
        </div>
        {% endif %}
    </div>
</div>

{% if agm.attendees %}
<div class="card mb-4">
    <div class="card-header"><h5 class="mb-0">Närvarande</h5></div>
    <div class="card-body">
        <p style="white-space: pre-line;">{{ agm.attendees }}</p>
    </div>
</div>
{% endif %}

{% if agm.resolutions %}
<div class="card mb-4">
    <div class="card-header"><h5 class="mb-0">Beslut</h5></div>
    <div class="card-body">
        <p style="white-space: pre-line;">{{ agm.resolutions }}</p>
    </div>
</div>
{% endif %}
{% endblock %}

familjekontor/app/templates/governance/board.html
{% extends "base.html" %}
{% from "macros/breadcrumbs.html" import render_breadcrumbs %}
{% block title %}Styrelse - PsalmGears{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumbs([
    {'title': 'Start', 'url': url_for('dashboard.index')},
    {'title': 'Styrelse'}
]) }}
{% endblock %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2><i class="bi bi-people"></i> Styrelse</h2>
    <div class="d-flex gap-2">
        {% if show_all %}
        <a href="{{ url_for('governance.board') }}" class="btn btn-outline-secondary btn-sm">Visa aktiva</a>
        {% else %}
        <a href="{{ url_for('governance.board', all='1') }}" class="btn btn-outline-secondary btn-sm">Visa alla</a>
        {% endif %}
        {% if not current_user.is_readonly %}
        <a href="{{ url_for('governance.board_new') }}" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Ny ledamot</a>
        {% endif %}
    </div>
</div>

{% if members %}
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Namn</th>
                <th>Roll</th>
                <th>Titel</th>
                <th>Tillträde</th>
                <th>Avgång</th>
                <th>E-post</th>
                <th>Telefon</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for m in members %}
            <tr>
                <td><strong>{{ m.name }}</strong></td>
                <td>
                    <span class="badge {% if m.role == 'ordforande' %}bg-primary{% elif m.role == 'vd' %}bg-info{% elif m.role == 'revisor' %}bg-warning text-dark{% else %}bg-secondary{% endif %}">
                        {{ m.role_label }}
                    </span>
                </td>
                <td>{{ m.title or '' }}</td>
                <td>{{ m.appointed_date.strftime('%Y-%m-%d') }}</td>
                <td>
                    {% if m.end_date %}
                    {{ m.end_date.strftime('%Y-%m-%d') }}
                    {% else %}
                    <span class="text-success">Aktiv</span>
                    {% endif %}
                </td>
                <td>{{ m.email or '' }}</td>
                <td>{{ m.phone or '' }}</td>
                <td class="text-end">
                    {% if not current_user.is_readonly %}
                    <a href="{{ url_for('governance.board_edit', member_id=m.id) }}" class="btn btn-outline-secondary btn-sm" title="Redigera"><i class="bi bi-pencil"></i></a>
                    {% if m.is_active %}
                    <form method="POST" action="{{ url_for('governance.board_end', member_id=m.id) }}" class="d-inline">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-outline-warning btn-sm" title="Avsluta uppdrag"
                                onclick="return confirm('Avsluta uppdraget för {{ m.name }}?')">
                            <i class="bi bi-x-circle"></i>
                        </button>
                    </form>
                    {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div class="alert alert-info">Inga styrelseledamöter registrerade.</div>
{% endif %}
{% endblock %}

familjekontor/app/templates/governance/shares.html
{% extends "base.html" %}
{% from "macros/breadcrumbs.html" import render_breadcrumbs %}
{% block title %}Aktiebok - PsalmGears{% endblock %}
{% block breadcrumbs %}
{{ render_breadcrumbs([
    {'title': 'Start', 'url': url_for('dashboard.index')},
    {'title': 'Aktiebok'}
]) }}
{% endblock %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2><i class="bi bi-pie-chart"></i> Aktiebok</h2>
    <div class="d-flex gap-2">
        <a href="{{ url_for('governance.share_register') }}" class="btn btn-outline-secondary"><i class="bi bi-printer"></i> Aktiebok (utskrift)</a>
        {% if not current_user.is_readonly %}
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                <i class="bi bi-plus-lg"></i> Lägg till
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ url_for('governance.share_class_new') }}">Nytt aktieslag</a></li>
                <li><a class="dropdown-item" href="{{ url_for('governance.shareholder_new') }}">Ny aktieägare</a></li>
                <li><a class="dropdown-item" href="{{ url_for('governance.holding_new') }}">Nytt innehav</a></li>
            </ul>
        </div>
        {% endif %}
    </div>
</div>

{# Share Classes #}
<div class="card mb-4">
    <div class="card-header"><h5 class="mb-0">Aktieslag</h5></div>
    <div class="card-body">
        {% if share_classes %}
        <div class="table-responsive">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>Aktieslag</th>
                        <th class="text-end">Röster/aktie</th>
                        <th class="text-end">Kvotvärde</th>
                        <th class="text-end">Totalt antal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sc in share_classes %}
                    <tr>
                        <td><strong>{{ sc.name }}</strong></td>
                        <td class="text-end">{{ sc.votes_per_share }}</td>
                        <td class="text-end">{% if sc.par_value %}{{ sc.par_value|sek }}{% else %}-{% endif %}</td>
                        <td class="text-end">{{ "{:,}".format(sc.total_shares).replace(",", " ") }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="text-muted mb-0">Inga aktieslag registrerade. <a href="{{ url_for('governance.share_class_new') }}">Skapa ett aktieslag</a>.</p>
        {% endif %}
    </div>
</div>

{# Ownership Summary #}
<div class="card mb-4">
    <div class="card-header"><h5 class="mb-0">Ägaröversikt</h5></div>
    <div class="card-body">
        {% if ownership %}
        <div class="row">
            <div class="col-md-8">
                <div class="table-responsive">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>Aktieägare</th>
                                <th class="text-end">Aktier</th>
                                <th class="text-end">Ägarandel</th>
                                <th class="text-end">Röster</th>
                                <th class="text-end">Röstandel</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in ownership %}
                            <tr>
                                <td>
                                    <strong>{{ row.shareholder.name }}</strong>
                                    {% if row.shareholder.is_company %}<span class="badge bg-info">Juridisk person</span>{% endif %}
                                </td>
                                <td class="text-end">{{ "{:,}".format(row.total_shares).replace(",", " ") }}</td>
                                <td class="text-end">{{ row.pct }} %</td>
                                <td class="text-end">{{ "{:,}".format(row.total_votes).replace(",", " ") }}</td>
                                <td class="text-end">{{ row.vote_pct }} %</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-4">
                <canvas id="ownershipChart" height="250"></canvas>
            </div>
        </div>
        {% else %}
        <p class="text-muted mb-0">Inga aktieinnehav registrerade.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block scripts %}
{% if ownership %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    var ctx = document.getElementById('ownershipChart').getContext('2d');
    new Chart(ctx, {
        type: 'pie',
        data: {
            labels: {{ ownership|map(attribute='shareholder')|map(attribute='name')|list|tojson }},
            datasets: [{
                data: {{ ownership|map(attribute='pct')|list|tojson }},
                backgroundColor: ['#0d6efd','#198754','#ffc107','#dc3545','#6610f2','#0dcaf0','#fd7e14','#6c757d']
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: { position: 'bottom', labels: { boxWidth: 12 } },
                title: { display: true, text: 'Ägarfördelning (%)' }
            }
        }
    });
});
</script>
{% endif %}
{% endblock %}